onboarding = false

[terminal]
default_shell = "nu"

[keys]
prefix = "ctrl+a"
focus_pane_left = ["prefix+ctrl+h", "ctrl+left"]
focus_pane_down = ["prefix+ctrl+j", "ctrl+down"]
focus_pane_up = ["prefix+ctrl+k", "ctrl+up"]
focus_pane_right = ["prefix+ctrl+l", "ctrl+right"]
split_vertical = "prefix+\\"
rename_tab = "prefix+,"
previous_workspace = "prefix+ctrl+p"
next_workspace = "prefix+ctrl+n"
previous_tab = "f2"
next_tab = "f3"
close_tab = "prefix+ctrl+x"

[theme]
name = "dracula"
auto_switch = false

[[keys.command]]
# This is technically cmd+k
# ghostty is sending it as F1 to work around our cmd issue
key = "f1"
type = "shell"
command = "herdr pane run $HERDR_ACTIVE_PANE_ID clear"
description = "clear screen and scrollback"

[[keys.command]]
key = "prefix+ctrl+r"
type = "shell"
command = "/Users/michaelschneider/dotfiles/herdr/herdr-emacs-search.sh"
description = "enter copy-mode with emacs keys and search"

[[keys.command]]
# Ghostty sends cmd+v as F4
key = "f4"
type = "shell"
command = "/Users/michaelschneider/dotfiles/herdr/herdr-paste.sh"
description = "smart paste: clipboard or pass to emacs"
