alias ss='cd ~/.ssh'
alias s='~/personalize/scripts/ssh_aws.bash'

alias ls='ls -G'
alias la='ls -la'
alias b='cd -'
alias e='cd ~/appropos/awt'

alias nr='npm run'
alias nt='npm test'
alias nrt='npm run test-one'
alias nrd='npm run dev'
alias nrs='npm run test:server'
alias nru='npm run test:utilities'
alias nrc='npm run test:client'
alias nrtd='npm run test-database'
alias td='npm run test-database 2>/dev/null'

alias cod='git checkout develop'
alias pd='git pull origin develop'
alias scour='~/personalize/scripts/scour.bash'
alias ns='cd ~/appropos/awt/server; env AWS_PROFILE=appropos ./bin/run-dev-server'
alias o='~/personalize/scripts/next_rebase_file.bash'
alias fd='~/personalize/scripts/next_git_diff_file.bash'
alias fa='~/personalize/scripts/next_git_add_file.bash'
alias fr='~/personalize/scripts/next_git_checkout_file.bash'
alias cf='~/personalize/scripts/next_vs_code_file.bash'
alias omf='git ls-files --others --exclude-standard | xargs sub; git ls-files -m | xargs sub'
alias reseed='env AWS_PROFILE=appropos npm run db:seed -- --email michael.schneider@envoyplatform.com'

alias cb='git symbolic-ref --short HEAD'
alias gits='git status'
alias co='git checkout'
alias cob='git checkout -b'
alias gitc='git commit -m'
alias gitb='git branch'
alias gitd='git diff'
alias gita='git add -A .; git status'
alias gitl='git log'
alias gpull='git pull origin (git symbolic-ref --short HEAD) --rebase'
alias gpush='git push origin (git symbolic-ref --short HEAD)'
alias cof='bash ~/personalize/scripts/checkout_feature.bash'
alias stash='cd ~/appropos/awt; git add -A .; git stash; git status'
alias pop='cd ~/appropos/awt; git stash pop; git reset HEAD .; git status'
# alias cntb='bash ~/personalize/scripts/cut_new_test_bucket.bash'
# alias tb='git checkout (git branch | grep "test-bucket" | sed "s/^.\{2\}//g")'
# alias mttb='bash ~/personalize/scripts/move_to_test_bucket.bash'
alias gt="~/personalize/scripts/colorize_go_tests.bash"
alias gtr="~/personalize/scripts/colorize_go_test_run.bash"
alias lastc='git log -p -1'

alias conint='ssh -i ~/.ssh/con-envoy-stag-eu-west-1.pem ec2-user@ec2-52-16-118-244.eu-west-1.compute.amazonaws.com'
alias envint='ssh -i ~/.ssh/app-envoy-prod-us-east-1.pem ec2-user@ec2-52-4-132-185.compute-1.amazonaws.com'
alias awtint='ssh -i ~/.ssh/app-envoy-prod-us-east-1.pem ubuntu@ec2-23-23-175-155.compute-1.amazonaws.com'
alias wwwint='ssh -i ~/.ssh/www-envoy-vpc.pem ec2-user@ec2-54-174-109-36.compute-1.amazonaws.com'
alias appdev='ssh -i ~/.ssh/app-envoy-stag-us-east-1.pem ec2-user@52.6.239.36'
alias wwwdev='ssh -i ~/.ssh/www-envoy-vpc-uat.pem ec2-user@52.22.40.7'
alias condev='ssh -i ~/.ssh/con-envoy-stag-eu-west-1.pem ec2-user@52.30.49.202'

alias update_ssh_config='cd ~/appropos/utilities/scripts; ./update_ssh_config.sh -u michael.schneider -o'
