alias ss='cd ~/.ssh'

alias ls='ls -G'
alias la='eza -l --icons --git -a'
alias lt='eza --tree --level=2 --long --icons --git'
alias b='cd -'
alias e='cd ~/appropos/envoy-web'
alias weather='curl wttr.in/Belmont,Michigan'
alias se='ls ~/code/tools-and-infrastructure/scripts/developer/environments | fzf | while read -r env; do select_env "$env"; done'
alias gitbd='~/dotfiles/scripts/delete_local_git_branches.sh'
alias bounceenv='~/dotfiles/scripts/setup_local_env.sh'
alias ddownloads='~/dotfiles/scripts/delete_download_files.sh'
alias hss='~/dotfiles/scripts/ssh_fzf.sh'
alias tssh='~/dotfiles/scripts/tunnel_ssh.sh'
alias tkill='if pids=$(lsof -t -i :27018); then echo "$pids" | xargs kill && echo "Tunnel killed"; else echo "No tunnel active"; fi'
alias sl='pmset sleepnow'
alias van='emacs --init-directory=/Users/michaelschneider/vanilla-emacs'
alias jdev='mb-jira-cli --toggleview="column" --filter="Dev Review"'
alias jme='mb-jira-cli --toggleview="table" --filter="Me"'
alias ntc='tmuxinator npm-test-concurrent --append'

alias nr='npm run'
alias nt='npm run test:concurrent'
alias nrt='npm run test-one'
alias nrs='npm run test:server'
alias nru='npm run test:utilities'
alias nrc='npm run test:client'

alias cod='git checkout develop'
alias pd='git pull origin develop'
alias ns='cd ~/appropos/envoy-web/server && ./bin/run-dev-server'
alias o='~/dotfiles/scripts/next_rebase_file.sh'
alias gd='~/dotfiles/scripts/next_git_diff_file.sh'
alias fa='~/dotfiles/scripts/next_git_add_file.sh'
alias fr='~/dotfiles/scripts/next_git_checkout_file.sh'
alias fo='~/dotfiles/scripts/next_git_ours_file.sh'
alias ft='~/dotfiles/scripts/next_git_theirs_file.sh'
alias cf='~/dotfiles/scripts/next_vs_code_file.sh'
alias ef='~/dotfiles/scripts/next_emacs_file.sh'
alias omf='git ls-files --others --exclude-standard | xargs sub && git ls-files -m | xargs sub'
alias reseed='npm run db:seed -- --email michael.schneider@envoyplatform.com'
alias ptq='npm run task process-tasks-queue'
alias task='AWS_PROFILE=appropos npm run task'
alias tasks='npm run tasks'
alias job='cd ~/appropos/envoy-web/server; env AWS_PROFILE=appropos APPROPOS_ENV=local ./bin/run-node bin/task-runner.js background-job-runner --integrationARN="arn:aws:sns:us-east-1:506597054164:appropos-integration-local-error" --ignoreJobInterval=true'
alias cemacs="xargs sh -c 'emacs $@ < /dev/tty' emacs"
alias preview="fzf --preview 'bat --style=numbers --color=always {}'"
alias ms="~/dotfiles/scripts/mongo_shell_inline.sh"
alias msf="~/dotfiles/scripts/mongo_shell_file.sh"
alias mt='~/dotfiles/scripts/mongo_tui_launch.sh'
alias editor='~/dotfiles/scripts/editor.sh'
alias deleteMany='~/dotfiles/scripts/select_from_table.sh'

alias ds='node /Users/michaelschneider/code/tools-and-infrastructure/webdev-tools/menu.js'
alias gl='bash ~/dotfiles/scripts/grep-git-log.sh'
alias ccont='git cherry-pick --continue'
alias rcont='git rebase --continue; git status'
alias cmf='git ls-files --others --exclude-standard | xargs code; git ls-files -m | xargs code'

alias cb='git symbolic-ref --short HEAD'
alias gits='git status'
alias co='git checkout'
alias cob='git checkout -b'
alias gitc='git commit -m'
alias gitb='git branch'
alias gitd='git diff'
alias gita='git add -A . && git status'
alias gitl='git log'
alias gpull='git pull origin `git symbolic-ref --short HEAD` --rebase'
alias gpush='git push origin `git symbolic-ref --short HEAD`'
alias cof='bash ~/dotfiles/scripts/checkout_feature.sh'
alias stash='git add -A .; git stash; git status'
alias pop='git stash pop; git reset HEAD .; git status'
alias rmautodump='rm auto_dump_*.tar.gz; rm -rf auto_dump_*'
alias fcode='fzf | cut -d ":" -f 1 | xargs code'

alias gt="~/dotfiles/scripts/colorize_go_tests.bash"
alias gtr="~/dotfiles/scripts/colorize_go_test_run.bash"
alias lastc='git log -p -1'

# alias emacs='emacs -nw'
alias fix_know_hosts="cd ~/.ssh; sed -i '' '/UserKnownHostsFile/d' config; cd -"
alias onering='/Users/michaelschneider/code/tools-and-infrastructure/scripts/developer/one-ring/onering.sh'
