* Emacs shortcuts
C-w is like cut
M-w is like copy
C-y is paste from kill ring
C-x C-f find file
M-g g goto line number
M-m brings up the main menu in Holy mode, h for help, T for tutorial
C-h is the help character
C-h x previous-line
C-h k C-p (describes what shortcut is linked to)
C-h v (describe-variable) lets you type a variable name and get it's value (like typescript-ts-mode-indent-offset)
C-j executes current line in scratch
S-e highlights current word
C-/ undo

M-: (eval-expression): Prompts you to type a Lisp expression in the minibuffer, which is then evaluated.
M-x describe-mode
M-: (fboundp 'tide-eldoc-function) is a way to check if internal functions exist
(message "### Adding tide-eldoc-function to eldoc-documentation-functions.")
M-RET h h lsp-describe-thing-at-point
C-x h is mark (highlight) whole buffer
M-x package-list-packages
(custom-set-faces! '(default :background nil)) ; If I ever want transparent background in emacs

** Buffers
C-x b switch to buffer; now bound to helm-buffers-list
C-x C-b list all buffers
C-x k kill buffer

** Windows
C-x 1 delete other windows; toggle maximize window
    under File -> Remove other windows
    Can find it under the M-x commands
C-x 2 split pane horizontally
C-x 3 split pane vertically
    M-x split-root-window-<right/below>
C-x o to move between windows

** Troubleshooting
See that no emacs are running in the background:
ps aux | grep emacs
C-x b to Messages to see errors that may have occurred
M-: org-indent-indentation-per-level # to get value of a variable

** pipe file to emacs
how come when I 'xargs emacs' to pass a file name, it errors with "emacs: standard input is not a tty"
xargs emacsclient -nw -a '' # works, but doesn't load any of my config stuff
https://mdk.fr/en/blog/emacs-standard-input-is-not-a-tty.html
    xargs sh -c 'emacs "$@" < /dev/tty' emacs # play more with alias
    xargs sh -c 'emacs "$@" < /dev/tty' emacs # try as a bash file

** True color
Run commands with M-: #
(getenv "COLORTERM")
# should show "truecolor"
(display-color-cells)
# should show 16777216
'Doom One' or 'Dracula' takes advantage of true color?
(load-theme 'doom-one t)   ;; or doom-dracula, doom-solarized-light, etc.
M-x load-theme RET doom-one RET
doom-dracula
doom-gruvbox
doom-nord
doom-solarized-dark
doom-tokyo-night

** Treemacs
M-m p t (now C-o p t) to display file browser pane
y r copies file and path to clipboard
p p to switch projects (if you see the wrong tree)

** Dired
launch with C-x d or M-x dired
go up a directory with ^
create directory with +
delete with d and executes delete with x
sort with o
close with q

** Dirvish
C-x f launch

** Flycheck/EsLint:
leader e l to view all flycheck errors
M-n jumps cursor to next error
M-p jumps cursor to previous error
leader e x explains error at current position

** Tide
M-x tide-documentation-at-point
(setq tide-always-show-documentation t)

** Magit
C-, g s # starts magit
s to stage files
k to delete untracked files
k to discard hunk
b c # similar to git checkout -b
c c to commit
    C-c C-c to save commit message and proceed
    C-c C-k to cancel
F p to pull
P p to push
g refreshes magit after resolving conflicts
A A to git cherry-pick continue
    C-c C-c to save commit message and proceed
A a to cherry-pick abort
r r for git rebase continue
    C-c C-c to save commit message and proceed
z k drop stash

*** Forge
forge-pull a to download all PR's
d d to view a PR diff (up and enter to easily enter 'develop' as branch to diff against)
e from PR diff to open a file in side-by-side view
m s to Squash and Merge the PR
gpg password is 'password' if prompted

** ORG mode
How do I set a todo? Appears to be only in ** precursed things
C-c C-c toggles checkboxes


* TODO try jtsx; apparently is supports better commenting in tsx files
* TODO Could try out the Inconsolata nerd font

* Golang:


* Starship
~/.config/starship.toml
${env_var.DEPLOY_ENV}\
[env_var.DEPLOY_ENV]
variable = "DEPLOY_ENV"
default = ""
format = '[ ($env_value)](fg:#090c0c bg:#a3aed2)'

* FZF
nvim $(fzf -m --preview="bat --color=always {}") # -m means multiple that you can mark in fzf
random ** at commandline tells fzf we want to open a fuzzy finder here (use tab not enter to engage)
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -l -g""'
https://www.youtube.com/watch?v=MvLQor1Ck3M
fzf --preview 'bat --style=numbers --color=always {}'
fzf --preview 'bat --style=numbers --color=always {}' --bind 'enter:execute(tmux new-window "vim {}" || tmux split-window "vim {}")'
tmux display-popup -E -w 80% -h 60% -x 10 -y 5 "cd ~/appropos/envoy-web && fzf --preview 'bat --style=numbers --color=always {}'"
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow'
export FZF_DEFAULT_OPTS='--height 50% --layout=reverse --border --inline-info'
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --preview 'bat --style=numbers --color=always {}
how do I get fzf to ignore certain folders?
How do I toggle folder mode in FZF?
FZF matches on build/ folder when I type "client standup"
    But isn't this okay? It's rg that I want to act like a project. fzf should fuzzy find any folder I cd into

* Git
git push --force-with-lease # a safe force push

* Tmux
prefix+n for next window
prefix+p for previous window
prefix+S for session manager
prefix+z for zooming in/out
prefix+c creates new window
prefix+< renames window
ctrl+space starts highlight in copy-mode
prefix+space cycles orientation of pane
prefix+: (command prompt) resize-pane
prefix+I to reload conf
prefix+U to force reload. Type 'all' at prompt
prefix+o swaps the right and left pane
prefix+shift+{ swaps a pane to the left
prefix+shift+} swaps a pane to the right
 - [X]  Get panes to start in same directory (envoy-web), windows always at home @done(25-10-09 20:
 - [X]  set shortcut to resize panes
Tmux hack for anytime it intercepts a keystroke:
    # Show a short message in the status line whenever tmux intercepts any key
    set -g display-time 500  # Message lasts half a second
    # Generic catch-all for testing: prints key + key table
    bind -n C-t run-shell 'tmux display-message "You pressed: C-t (table=#{key_table})"'
https://www.youtube.com/watch?v=UtINDdy-xBc has a sweet statusbar
    .tmux on github has lots of snazzy goodies
    tmux-powerline is the statusbar one
    SessionX
        set -g @plugin 'omerxx/tmux-sessionx'
        tmux display-popup -E "tmux-sessionx"
        tmux display-popup -E "env | grep SHELL; echo \$PATH; command -v fzf; tmux-sessionx; sleep 10"
        tmux source-file ~/.config/tmux/plugins/tmux-sessionx/sessionx.tmux
        ls /Users/michaelschneider/.config/tmux/plugins/
        echo $TMUX_PLUGIN_MANAGER_PATH
        you can set custom-paths. These will auto attach or create at these paths from sessionX

* Yassnippets
Run with M-shift-: #
(message "Snippet dir: ~/.emacs.d/private/snippets/%s/" major-mode)
M-x yas-reload-all
~/.emacs.d/private/snippets/js2-mode/
M-x yas-describe-tables
M-x yas-expand forces snippet instead TAB key
clg for console.log() snippet

* VsCode
C-K C-S to see shortcut tool

* dump dev to local:
mongodump --out=/client/dump/dump_7_21_2025 --excludeCollection=ImportRow --excludeCollection=HouseLogRow --excludeCollection=Event --excludeCollection=EventAggregate --excludeCollection=CardConnectIntegration --uri=$MONGO_CONNECTION_STRING
aws secretsmanager get-secret-value --secret-id "envoy-dev-na-cf-bauer-na_CONNECTION_STRING" | jq -r '.SecretString'
history | grep SUBPREFIX gets you started running tasks on dev server

* Ghostty
https://www.youtube.com/watch?v=enwDjM7pNNE (cursor trails)
    https://github.com/ghostty-org/ghostty/releases
ghostty +list-keybinds
ghostty show-config --default --docs
macos-icon-frame
    docs are: https://ghostty.org/docs/config/reference
currently keeping shaders in: ~/.config/ghostty
** ghostty +list-themes
box
dark pastel
deep
farmhouse
firefly
github dark
glacier
hardcore ** I like this one

* RipGrep
rg -F looks for exact text matches instead of regex
rg -F -C5 gives 5 lines context around the match
rg -i goes case insensitive

* entr
ls *.rg | entr ruby main.rb
mongosh $NAMING_PREFIX query.js
clear && mongosh $NAMING_PREFIX query.js
echo query.js | entr zsh -c 'clear && mongosh "$NAMING_PREFIX" query.js'
echo query.js | entr zsh -c 'clear && mongosh "$NAMING_PREFIX" query.js | jq ".[].code"'
printjson(JSON.stringify(
    db.Collection.find({isActive: false}).toArray()
))
For integration servers:
mongosh $MONGO_CONNECTION_STRING

* TODO mc (midnight commander) vs yazi?

* mongosh
mongosh wwwinc-stag-eu-cf --quiet --eval "JSON.stringify(db.Product.find({}).toArray())" | jq ".[].sizingSystems[].variations"
mongosh $NAMING_PREFIX --quiet --eval "JSON.stringify(db.Product.find({}).toArray())" | jq ".[].sizingSystems[].variations"
mongosh "$NAMING_PREFIX" --eval 'db.Client.updateMany({}, {$set: {"config.integrationMoveFiles": false, "config.integrationSrcPath": "/Users/michaelschneider/appropos/envoy-web"}})'
mso "Client.deleteOne({code: 'faker-na'})"
* tongo

* cron
sudo systemctl status crond

* On integration server, to see the envoy-web codebase in docker:
docker run --env 'MONGO_CONNECTION_STRING=mongodb://appropos:0n3QvxZGIGqi@ip-10-0-3-141.ec2.internal/envoy-web?replicaSet=cid-resources-stag-na-cf&authSource=admin' --env AWS_REGION=us-east-1 --rm --mount type=bind,source=/client,target=/client -ti cid-resources-stag-na-cf:latest bash
or use the $DOCKER_RUN_ONE to run commands like from cron
Chad might make a $DOCKER_RUN to make it even easier, so we don't need to fiddle with the lock
/client is mounted inside docker containers at /client.  So it can do work on integration files
~/utilities_parent/utilities/scripts/docker_shell.sh
** cleanup_old_files.sh
/home/ec2-user/utilities_parent/utilities/scripts/cleanup_old_files.sh
$UTILITIES_PATH/scripts/cleanup_old_files.sh -k 30 /client/EU/archive
** deal with docker locally
docker exec -it 7ebf68dae360 /bin/bash

* Handy for pausing in scripts:
import readline from 'readline';
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});
return new Promise((resolve) => {
    rl.question('Press Enter to continue... (or Ctrl+c to exit)', () => {
        resolve();
    });
}).then(() => {rl.close()});

* 7 Essential command line tools
grep "search term" file.txt
grep -i subResource # makes it case insensitive
grep -iv subResource # flips to exclude instead of include
sed 's/one/omerxx/g' my.json # /g is for global
gsed -i 's/one/omerxx/g' my.json # -i writes back to the file
cat my.json --style plain
bat also works as a pager (replaces more and less)
awk '{print $1$2}' text.txt
awk '$2 >=200 {print $1}' data.txt
| cut -d ':' -f 1,3 |

* JQ:
| jq ".status.statusBar[1]"
| jqp # to a GUI like interface
jq -r # gets rid of wrapping quotes if you're just outputting strings
| jq '.[0] | {message: .commit.message, name: .commit.committer.name}'
jq -c # is for 'compact'; takes out line returns and whatnot
jq '.team[] | select(.salary<115000)' pp.json
jq '.team[] | select(.name=="James Dunn")' pp.json
jq '.team[] | del(.skills) | del(.salary)' pp.json
jq keys pp.json
jq '.team[] | keys' pp.json
jq '.team[] | select(.skills | index("Java"))' pp.json # index seems to match on string "Java" in skills array
gojq can also parse yaml, and convert between yaml and json
jq "[.products[].skus[].props.qtyOpen] | add"

* YQ:
yq --input-format=csv --output-format=json '.[] | ."Open_Qty"' hockey_na_sales_status.251202010530.csv

* Jira UI
To filter and use JQL:
    click Search bar at top
    click "view all work items"
https://envoyplatform.atlassian.net/issues?filter=11900&jql=project%20in%20%28EP%2C%20EI%29%20AND%20fixVersion%20%3D%20v40%20AND%20%22Deployment%20Notes%22%20is%20not%20EMPTY
* Jira API
    https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/

* Dump Dev Database
Log into shared dev server in Studio 3T
find your db. Right click or Cmd+c
Right-click localhost or select and Cmd+v

* SFTP
sidelines_sftp@sftp.envoyb2b.com password: GoARKiBGhrqzdkH+4gkxdA==
get Product-2025-11-05-10-16-14.csv
mv Product-2025-11-05-10-16-14.csv /Users/sftp_test/sftp/PRODUCT/
job --type=SFTP_PRODUCT_IMPORT --brandCode=sidelines
select_env (probably envoy-prod), then:
can we come up with a commandline script to set my integration card?
sftp Matador2@sftp.envoyb2b.com password: cuh55VkkR7rbyyIOaD/1pg==
ssh envoy-prod-na-sftp
* FTPS
lftp -e "set ftp:ssl-protect-data yes; set ftp:ssl-force yes; open -u username,password ftps.example.com"

* Scripting ideas
I've moved around symlinks, what about unaliasing and re-aliasing?

* AWS
AWS_PROFILE=appropos-admin AWS_REGION=us-east-1 script_to_run.sh

* Node
rm -rf node_modules && npm cache clear --force && rm -f .stylelintcache .eslintcache && nvm install && nvm use && npm run install-dev

* Nginx
nginx is now booted up from docker dashboard on my system

* Aerospace
mac window tiling manager
https://www.youtube.com/watch?v=5nwnJjr5eOo
defaults write -g NSWindowShouldDragOnGesture -bool true
Now, you can move windows by holding ctrl+cmd and dragging any part of the window (not necessarily the window title)
has function built in that negates need for skhd. Set random OS level hotkeys to run stuff
alt-, lays out windows horizontally (do again to toggle between vertical/horizontal)
alt-/ lays out windows stacked
alt-shift-tab swaps workspace onto secondary monitor
alt-shift-h moves (swaps) window tile to the left
alt-shift-l moves (swaps) window tile to the right
alt-shift-space floats the window making it a popover
 - [ ]  ^^ okay, now can you move the popover?
alt-shift-arrow (one of vim keys) does horizontal

* Sketchy Bar
brew services start sketchybar
brew services stop sketchybar
brew services restart sketchybar
Is the Slack icon appearing or not based on if I'm in laptop of docked mode?


* gh:
gh auth status
gh repo view
gh pr list
gh pr view PR_NUMBER
gh pr status
gh pr merge PR_NUMBER --squash --delete-branch
gh pr diff | delta (or `gh pr diff PR_NUMBER | delta`)

* Carapace
auto completion for Go and pretty much everything else
* Zoxide
better cd. "Single greatest command line tool"
* Janky Borders
Adds some border customization to Aerospace
* Hammerspoon
Can launch or interact with apps
Can run menu items
Has cool looking display modal
https://www.youtube.com/watch?v=wnsJ0vxQms0
* Curl
https://www.youtube.com/watch?v=3xmD4E2aqxo
* TODO NuShell
https://www.youtube.com/watch?v=uJsZATwQ3R8
* Devs are better than AI; learn to hack
https://www.youtube.com/watch?v=iBkDhtjqXhA

* Expanso is like snippets for your terminal
 - [ ]  Is this something that works across ssh? because I could really use an mso/msa snippet!
* DONE Moonlander keyboard!
CLOSED: [2026-01-07 Wed 11:38]
 - [X]  Ordered!
 - [X]  consier mapping alt-{ instead of alt-shift-{ to line hopper
 - [X]  or better yet, it doesn't look like alt-i and alt-k do anything productive; map those!
 - [X]  map hyper-s to Slack.
 - [X]  Need to version control aerospace.toml!!!
 - [X]  Toy with lights

* TODO lazysql (TUI app for sqlite)

Postgres is not a database
https://www.youtube.com/watch?v=b7eXdUOzUTM
5 minutes

* Brow6el is a browser that runs in a terminal
* Opencode
     | Action | Keybind |
     |--------|---------|
     | Page Up | PageUp |
     | Page Down | PageDown |
     | Half Page Up | Ctrl+Alt+u |
     | Half Page Down | Ctrl+Alt+d |
     | Go to First Message | Ctrl+g or Home |
     | Go to Last Message | Ctrl+Alt+g or End |

     Scroll Speed Configuration

     You can also customize scroll behavior in your opencode.json:

     {
       "tui": {
         "scroll_speed": 3,
         "scroll_acceleration": {
           "enabled": true
         }
       }
     }
