format = """
[    ](bg:#212736 fg:red)\
${env_var.NAMING_PREFIX}\
[](bg:#394260 fg:#212736)\
$directory\
[](fg:#394260 bg:#212736)\
$git_branch\
$git_status\
[](fg:#212736 bg:#394260)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#394260)\
${custom.tunnel}\
\n$character"""

[directory]
style = "fg:blue bg:#394260"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[env_var.DEPLOY_ENV]
variable = "DEPLOY_ENV"
default = ""
format = '[ ($env_value)](fg:#090c0c bg:#a3aed2)'

[env_var.NAMING_PREFIX]
variable = "NAMING_PREFIX"
default = ""
format = '[ ($env_value) ](fg:red bg:#212736)'

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:green bg:#212736)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:green bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:yellow bg:#394260)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[custom.tunnel]
command = "echo 'TUNNEL ACTIVE'"
when = "lsof -i :27018"
format = "\n[   $output   ](fg:#212736 bg:yellow)[](fg:yellow)"

[character]
success_symbol = "[▶︎](bold green)" # Symbol on command success ✈︎ ✒︎ ➤ ► ▶︎ ⚡︎ ♜ ☀︎ ➜
error_symbol = "[✗](bold red)" # Symbol on command failure
